# https://www.home-assistant.io/integrations/default_config/
default_config:

# Enable VSCode debugging
debugpy:
  start: true
  wait: true

logger:
  default: info
  logs:
    custom_components.mediabrowser: debug